%%{init: {"themeVariables": {"xyChart": {"plotColorPalette": "#0969da"}}}}%%
xychart-beta
    title "Chunk size (tokens)"
    x-axis ["0", "100", "200", "300", "400", "500", "600", "700"]
    y-axis "chunks" 0 --> 170
    bar [100, 159, 142, 111, 58, 52, 67, 13]
