"""Export the compiled graph as Mermaid (plan P4.11, HLD §8.1.1).

    python -m samvidhan.graph.export [out.mmd ...]     # default: docs/design/graph.mmd

The graph shape doesn't depend on its deps, so none are built (no DB, models or keys needed).
"""

import sys
from collections.abc import Sequence
from pathlib import Path
from typing import cast

from samvidhan.graph.builder import build_graph
from samvidhan.graph.nodes import GraphDeps

DEFAULT_OUT = Path("docs/design/graph.mmd")
NOTE = "\t%% Generated by `python -m samvidhan.graph.export` (make graph). Do not edit by hand."


def mermaid() -> str:
    graph = build_graph(cast(GraphDeps, None))  # nodes never run during export
    text = graph.get_graph().draw_mermaid()
    # Mermaid front matter must come first, so the note goes after the diagram declaration.
    return text.replace("graph TD;\n", f"graph TD;\n{NOTE}\n", 1)


def main(argv: Sequence[str] | None = None) -> int:
    outs = [Path(p) for p in (argv if argv is not None else sys.argv[1:])] or [DEFAULT_OUT]
    text = mermaid()
    for out in outs:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8")
        sys.stdout.write(f"wrote {out}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
